### ISSUE TITLE
Archive lacks data from the past year

### ISSUE THREAD

**Issue by runasand** [MaxBittker/nyt-first-said#6]
Would appear the archive was last updated ~a year ago. Would be great with an update!

**Comment by MaxBittker** [comment]
They should be up to date now, thanks for nudge @runasand !

I'm definitely curious to hear what you're using the data for, if you care to share :) 

originally puled these for https://arxiv.org/abs/2003.03444

**Comment by runasand** [comment]
Funny tweets... for now :)

https://twitter.com/runasand/status/1252215400131067906

**Comment by MaxBittker** [comment]
Excellent... and true to goals of the project 😛
